<%@ Page Language="C#" MasterPageFile="~/plantillas/SILPA.master" AutoEventWireup="true" CodeFile="Diligenciar_FUS_Electronico.aspx.cs" Inherits="LicenciasAmbientales_LPA_Diligenciar_FUS_Electronico" Title="Diligenciar FUS Electronico" %>

<%--
<%@ Register Src="Controles/wucDemanda_Uso.ascx" TagName="wucDemanda_Uso" TagPrefix="uc1" %>
--%>
<asp:Content ID="Content1" ContentPlaceHolderID="headPlaceHolder" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:ScriptManager id="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <asp:UpdatePanel id="UpdatePanel1" runat="server" ChildrenAsTriggers="False" UpdateMode="Conditional">
        <ContentTemplate>
            <div><table style="WIDTH: 425px; HEIGHT: 92px"><tbody><tr><td><div><asp:Label id="Label1" runat="server" Text="Código SILPA" Width="102px" Height="19px"></asp:Label></div></td><TD><DIV><asp:TextBox id="TXT_CODIGO_SILPA" runat="server" Width="171px">SILPA-001232100</asp:TextBox></DIV></TD><TD style="WIDTH: 3px"><DIV><asp:Button id="BTN_BUSCAR_DATOS" onclick="BTN_BUSCAR_DATOS_Click" runat="server" Text="Buscar"></asp:Button></DIV></TD><TD style="WIDTH: 3px"><DIV><asp:Button id="BTN_LIMPIAR" runat="server" Text="Limpiar" OnClick="BTN_LIMPIAR_Click"></asp:Button></DIV></TD></tr><TR><TD style="HEIGHT: 3px" colSpan=4></TD></TR></tbody></table></div>
        </ContentTemplate>
<triggers>
<asp:AsyncPostBackTrigger ControlID="BTN_LIMPIAR" EventName="Click"></asp:AsyncPostBackTrigger>
</triggers>
    </asp:UpdatePanel>
    <asp:MultiView ID="MVW_FUS" runat="server">
        <asp:View ID="VEW_DATOS_SOLICITANTE" runat="server">
            &nbsp;<br />
            <table style="width: 305px; height: 109px">
                <tr>
                    <td colspan="3" style="height: 1048px">
                        <asp:Label id="LBL_SECCION_I" runat="server" Height="20px" Width="505px" Text="SECCION 1. DATOS DEL SOLICITANTE"></asp:Label> <TABLE style="BORDER-COLLAPSE: collapse" id="table1" width="100%" border=0><TBODY><TR><TD style="WIDTH: 38%; HEIGHT: 23px" align=right><B><asp:Label id="Label16" runat="server" Height="19px" Width="250px" Text="1. Nombre o Razón Social:"></asp:Label></B></TD><TD style="HEIGHT: 23px" colSpan=2><asp:Label id="Label2" runat="server" Width="84px" Text="Pepito Perez"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right><B><asp:Label id="Label17" runat="server" Height="19px" Width="250px" Text="Tipo de persona"></asp:Label></B></TD>
                            <td colspan="2" style="HEIGHT: 21px"><asp:Label ID="Label3" runat="server" Text="Natural" Width="84px"></asp:Label></td></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right><B><asp:Label id="Label18" runat="server" Height="19px" Width="250px" Text="Identificación:"></asp:Label></B></TD><TD style="HEIGHT: 21px" colSpan=2><asp:Label id="Label4" runat="server" Width="234px" Text="Cedula de ciudadanía: # 88180200"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 20px" align=right><B><asp:Label id="Label19" runat="server" Height="19px" Width="250px" Text="Dirección:"></asp:Label></B></TD><TD style="HEIGHT: 20px" colSpan=2>
                            <asp:Label id="Label5" runat="server" Width="98px" Text="Cra 7a # 6-66"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right rowSpan=3><B><asp:Label id="Label20" runat="server" Height="19px" Width="250px" Text="Ubicación:"></asp:Label></B></TD><TD align=right width=87><asp:Label id="Label6" runat="server" Text="Pais"></asp:Label></TD><TD width="68%"><asp:Label id="Label7" runat="server" Text="Colombia"></asp:Label></TD></TR><TR><TD style="HEIGHT: 21px" align=right width=87><asp:Label id="Label9" runat="server" Text="Departamento:"></asp:Label> </TD><TD style="HEIGHT: 21px" width="68%"><asp:Label id="Label8" runat="server" Text="Bogotá D.C. "></asp:Label></TD></TR>
                            <tr><td align="right" style="HEIGHT: 21px" width="87"><asp:Label ID="Label10" runat="server" Text="Municipio:"></asp:Label></td><td style="HEIGHT: 21px" width="68%"><asp:Label ID="Label11" runat="server" Text="Santafé de Bogotá"></asp:Label></td></tr><tr><td align="right" style="WIDTH: 38%"><b><asp:Label ID="Label21" runat="server" Height="19px" Text="Teléfono:" Width="250px"></asp:Label></b></td><td colspan="2"><asp:Label ID="Label12" runat="server" Text="3472960"></asp:Label></td></tr><tr><td align="right" style="WIDTH: 38%"><b><asp:Label ID="Label22" runat="server" Height="19px" Text="Fax:" Width="250px"></asp:Label></b></td>
                            <td colspan="2"><asp:Label ID="Label13" runat="server" Text="3472961"></asp:Label></td></tr><tr><td align="right" style="WIDTH: 38%; HEIGHT: 16px"><b><asp:Label ID="Label23" runat="server" Height="19px" Text="Cuenta de correo:" Width="250px"></asp:Label></b></td><td colspan="2" style="HEIGHT: 16px"><asp:Label ID="Label14" runat="server" Text="un_correo@yahoo.com"></asp:Label></td></tr><tr><td align="right" style="WIDTH: 38%"><b><asp:Label ID="Label24" runat="server" Height="19px" Text="Cuenta de correo alternativo:" Width="250px"></asp:Label></b></td><td colspan="2"><asp:Label ID="Label15" runat="server" Text="otro_correo@yahoo.com"></asp:Label></td></tr></TBODY></TABLE>
<BR /><TABLE style="WIDTH: 102%; BORDER-COLLAPSE: collapse" id="Table2" border=0><TBODY><TR><TD style="WIDTH: 38%; HEIGHT: 23px" align=right><B><asp:Label id="Label29" runat="server" Height="19px" Width="250px" Text="2. Representante Legal:"></asp:Label></B></TD><TD style="HEIGHT: 23px" colSpan=2></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right><B><asp:Label id="Label31" runat="server" Height="19px" Width="250px" Text="Nombre:"></asp:Label></B></TD><TD style="HEIGHT: 21px" colSpan=2><asp:Label id="Label32" runat="server" Width="51px" Text="Natural"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right>
                            <b><asp:Label ID="Label33" runat="server" Height="19px" Text="Identificación:" Width="250px"></asp:Label></b></TD><TD style="HEIGHT: 21px" colSpan=2><asp:Label id="Label34" runat="server" Width="84px" Text="88120200"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 20px" align=right><B><asp:Label id="Label35" runat="server" Height="19px" Width="250px" Text="Dirección:"></asp:Label></B></TD><TD style="HEIGHT: 20px" colSpan=2><asp:Label id="Label36" runat="server" Width="98px" Text="Cra 17a # 7-77"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right rowSpan=3><B><asp:Label id="Label37" runat="server" Height="19px" Width="250px" Text="Ubicación:"></asp:Label></B></TD>
                            <td align="right" width="87"><asp:Label ID="Label38" runat="server" Text="Pais"></asp:Label></td><td width="68%"><asp:Label ID="Label39" runat="server" Text="Colombia"></asp:Label></td></TR><TR><TD style="HEIGHT: 21px" align=right width=87><asp:Label id="Label40" runat="server" Text="Departamento:"></asp:Label> </TD><TD style="HEIGHT: 21px" width="68%"><asp:Label id="Label41" runat="server" Width="159px" Text="Bogotá D.C. "></asp:Label></TD></TR><TR><TD style="HEIGHT: 21px" align=right width=87><asp:Label id="Label42" runat="server" Text="Municipio:"></asp:Label></TD><TD style="HEIGHT: 21px" width="68%"><asp:Label id="Label43" runat="server" Text="Santafé de Bogotá"></asp:Label></TD></TR>
                            <tr><td align="right" style="WIDTH: 38%"><b><asp:Label ID="Label44" runat="server" Height="19px" Text="Teléfono:" Width="250px"></asp:Label></b></td><td colspan="2"><asp:Label ID="Label45" runat="server" Text="4472960"></asp:Label></td></tr><tr><td align="right" style="WIDTH: 38%"><b><asp:Label ID="Label46" runat="server" Height="19px" Text="Fax:" Width="250px"></asp:Label></b></td><td colspan="2"><asp:Label ID="Label47" runat="server" Text="4472961"></asp:Label></td></tr><tr><td align="right" style="WIDTH: 38%; HEIGHT: 16px"><b><asp:Label ID="Label48" runat="server" Height="19px" Text="Cuenta de correo:" Width="250px"></asp:Label></b></td>
                            <td colspan="2" style="HEIGHT: 16px"><asp:Label ID="Label49" runat="server" Text="primer_correo@yahoo.com"></asp:Label></td></tr><tr><td align="right" style="WIDTH: 38%"><b><asp:Label ID="Label50" runat="server" Height="19px" Text="Cuenta de correo alternativo:" Width="250px"></asp:Label></b></td><td colspan="2"><asp:Label ID="Label51" runat="server" Text="segundo_correo@yahoo.com"></asp:Label></td></tr></TBODY></TABLE>
<BR /><TABLE style="BORDER-COLLAPSE: collapse" id="Table3" width="100%" border=0><TBODY><TR><TD style="WIDTH: 38%; HEIGHT: 23px" align=right><B><asp:Label id="Label25" runat="server" Height="19px" Width="250px" Text="3. Apoderado:"></asp:Label></B></TD><TD style="HEIGHT: 23px" colSpan=2></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right><B><asp:Label id="Label27" runat="server" Height="19px" Width="250px" Text="Tarjeta Profesional:"></asp:Label></B></TD><TD style="HEIGHT: 21px" colSpan=2><asp:Label id="Label28" runat="server" Width="84px" Text="2502356984CND"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right>
                            <b><asp:Label ID="Label30" runat="server" Height="19px" Text="Identificación:" Width="250px"></asp:Label></b></TD><TD style="HEIGHT: 21px" colSpan=2><asp:Label id="Label52" runat="server" Width="234px" Text="Cedula de ciudadanía: # 88180200"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 20px" align=right><B><asp:Label id="Label53" runat="server" Height="19px" Width="250px" Text="Dirección:"></asp:Label></B></TD><TD style="HEIGHT: 20px" colSpan=2><asp:Label id="Label54" runat="server" Width="98px" Text="Cra 7a # 6-66"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right rowSpan=3><B>
                            <asp:Label id="Label55" runat="server" Height="19px" Width="250px" Text="Ubicación:"></asp:Label></B></TD><TD align=right width=87><asp:Label id="Label56" runat="server" Text="Pais"></asp:Label></TD><TD width="68%"><asp:Label id="Label57" runat="server" Text="Colombia"></asp:Label></TD></TR><TR><TD style="HEIGHT: 21px" align=right width=87><asp:Label id="Label58" runat="server" Text="Departamento:"></asp:Label> </TD><TD style="HEIGHT: 21px" width="68%"><asp:Label id="Label59" runat="server" Text="Bogotá D.C. "></asp:Label></TD></TR><TR><TD style="HEIGHT: 21px" align=right width=87><asp:Label id="Label60" runat="server" Text="Municipio:"></asp:Label></TD>
                            <td style="HEIGHT: 21px" width="68%"><asp:Label ID="Label61" runat="server" Text="Santafé de Bogotá"></asp:Label></td></TR><TR><TD style="WIDTH: 38%" align=right><B><asp:Label id="Label62" runat="server" Height="19px" Width="250px" Text="Teléfono:"></asp:Label></B></TD><TD colSpan=2><asp:Label id="Label63" runat="server" Text="3472960"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right><B><asp:Label id="Label64" runat="server" Height="19px" Width="250px" Text="Fax:"></asp:Label></B></TD><TD style="HEIGHT: 21px" colSpan=2><asp:Label id="Label65" runat="server" Text="3472961"></asp:Label></TD></TR><TR>
                            <TD style="HEIGHT: 11px; TEXT-ALIGN: left" align=right colSpan=3>
</TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 16px" align=right></TD><TD style="HEIGHT: 16px" colSpan=2></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 16px" align=right><B><asp:Label id="Label66" runat="server" Height="19px" Width="250px" Text="Nombre del proyecto:"></asp:Label></B></TD><TD style="HEIGHT: 16px" colSpan=2><asp:Label id="Label67" runat="server" Text="SILPA"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right><B><asp:Label id="Label68" runat="server" Height="19px" Width="250px" Text="Sector:"></asp:Label></B></TD><TD colSpan=2><asp:Label id="Label69" runat="server" Text="otro_correo@yahoo.com"></asp:Label></TD></TR><TR>
                            <td align="right" style="WIDTH: 38%"><asp:Label ID="Label26" runat="server" Font-Bold="True" Height="19px" Text="Tipo del Proyecto:" Width="250px"></asp:Label></td><td colspan="2"><asp:Label ID="Label70" runat="server" Text="Tipo del proyecto"></asp:Label></td></TR><TR><TD style="WIDTH: 38%" align=right><asp:Label id="Label71" runat="server" Height="19px" Width="250px" Text="Localización del proyecto:" Font-Bold="True"></asp:Label></TD><TD colSpan=2></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right><asp:Label id="Label73" runat="server" Height="19px" Width="250px" Text="Departamento:" Font-Bold="True"></asp:Label></TD><TD style="HEIGHT: 21px" colSpan=2>
                            <asp:Label id="Label72" runat="server" Text="Cundinamarca"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%; HEIGHT: 21px" align=right><asp:Label id="Label74" runat="server" Height="19px" Width="250px" Text="Municipio:" Font-Bold="True"></asp:Label></TD><TD style="HEIGHT: 21px" colSpan=2><asp:Label id="Label76" runat="server" Text="Funza"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right><asp:Label id="Label75" runat="server" Height="19px" Width="250px" Text="Vereda y/o Corregimiento:" Font-Bold="True"></asp:Label></TD><TD colSpan=2><asp:Label id="Label77" runat="server" Text="Una Vereda"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right>
                            <asp:Label id="Label78" runat="server" Height="19px" Width="250px" Text="Corporación o MAVDT:" Font-Bold="True"></asp:Label></TD><TD colSpan=2><asp:Label id="Label81" runat="server" Text="Una corporacion"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right><asp:Label id="Label79" runat="server" Height="19px" Width="250px" Text="Valor del proyecto en letras: " Font-Bold="True"></asp:Label></TD><TD colSpan=2><asp:Label id="Label82" runat="server" Text="Ún millón"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right><asp:Label id="Label80" runat="server" Height="19px" Width="250px" Text="Valor del proyecto en números:" Font-Bold="True"></asp:Label></TD><TD colSpan=2>
                            <asp:Label id="Label83" runat="server" Text="1.000.000"></asp:Label></TD></TR><TR><TD style="WIDTH: 38%" align=right></TD><TD colSpan=2></TD></TR></TBODY></TABLE>
                    </td>
                </tr>
            </table>
            <br />
            <TABLE style="WIDTH: 437px"><TBODY><TR><TD style="WIDTH: 3px; HEIGHT: 229px"><DIV style="WIDTH: 129px; HEIGHT: 100px">&nbsp;<asp:Label id="Label85" runat="server" Width="135px" Text="TIPO DE PERMISO:"></asp:Label> <asp:CheckBoxList id="CheckBoxList1" runat="server" Width="327px"><asp:ListItem>Concesi&#243;n de agua superficial</asp:ListItem>
<asp:ListItem>Prospecci&#243;n y exploraci&#243;n de aguas subterr&#225;neas</asp:ListItem>
<asp:ListItem>Concesi&#243;n de aguas subterr&#225;neas</asp:ListItem>
<asp:ListItem>Permiso de vertimientos</asp:ListItem>
<asp:ListItem>Permiso de aprovechamiento forestal </asp:ListItem>
<asp:ListItem>Permiso de emisiones fuentes  fijas</asp:ListItem>
<asp:ListItem>Licencia Ambiental</asp:ListItem>
</asp:CheckBoxList> </DIV></TD><TD style="WIDTH: 3px; HEIGHT: 229px"></TD><TD style="WIDTH: 3px; HEIGHT: 229px"></TD></TR></TBODY></TABLE>
            <br />
            <br />
<asp:Panel id="PNL_FUS" runat="server" Height="50px" Width="125px" Visible="False">
<HR style="WIDTH: 545px" />
<BR /></asp:Panel> 
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click1" Text="SIG VISTA" /><br />
        </asp:View>
        <asp:View ID="VEW_SECCION_III" runat="server">
<%--
<uc1:wucDemanda_Uso ID="WucDemanda_Uso1" runat="server" />
     --%>
            
        </asp:View>
    </asp:MultiView>&nbsp;<br />
    &nbsp;
    <br />
</asp:Content>

